2020-12-13 02:17:50,294 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:57]
2020-12-13 02:24:34,297 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:57]
2020-12-13 02:25:57,907 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:57]
2020-12-13 04:38:22,673 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-13 05:00:39,435 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-13 14:50:58,300 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-13 14:58:11,256 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-13 16:06:07,272 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-13 16:06:43,723 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-13 16:26:35,390 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-13 16:27:47,392 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-13 16:29:13,464 ERROR: Exception on /reset_password_request [POST] [in /home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/routes.py", line 202, in reset_password_request
    send_password_reset_email(user)
  File "/home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/email.py", line 11, in send_password_reset_email
    token = user.get_reset_password_token()
AttributeError: 'User' object has no attribute 'get_reset_password_token'
2020-12-14 00:40:55,077 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-14 02:46:41,072 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-14 02:46:46,146 ERROR: Exception on /reset_password_request [POST] [in /home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/routes.py", line 202, in reset_password_request
    send_password_reset_email(user)
  File "/home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/email.py", line 15, in send_password_reset_email
    send_email(
  File "/home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/email.py", line 10, in send_email
    mail.send(msg)
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 308, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2020-12-14 02:47:41,056 ERROR: Exception on /reset_password_request [POST] [in /home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/routes.py", line 202, in reset_password_request
    send_password_reset_email(user)
  File "/home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/email.py", line 15, in send_password_reset_email
    send_email(
  File "/home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/email.py", line 10, in send_email
    mail.send(msg)
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/crispin/.local/share/virtualenvs/PacksonNjauMwangi-ZHoZ6FpG/lib/python3.8/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 308, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2020-12-14 03:00:36,237 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-14 03:02:55,522 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-14 03:04:31,324 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-14 03:07:49,119 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-14 07:06:12,122 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
2020-12-14 07:08:15,672 INFO: Sensual Masage [in /home/crispin/Documents/Python_projects/PacksonNjauMwangi/app/__init__.py:60]
